version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Add PostgreSQL database for production
  # Uncomment if you want to use a real database instead of mock data
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: stockdashboard
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./scripts:/docker-entrypoint-initdb.d
  #   restart: unless-stopped

# volumes:
#   postgres_data:
